name: "GitHub Cert - Podcast Generator"
author: "Aaron Johnson"
description: "Generates a feed for a podcast from a YAML file per Gitub LinkedIn Learning course by Ray Villalobos"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: "The committer's email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The committer's name"
    required: true
    default: ${{ github.actor }} 